### ISSUE TITLE
A very high first box blocks rest of level

### ISSUE THREAD

**Issue by kimmob** [skjolber/3d-bin-container-packing#1]
I think it's a bug that when first box in a container needs to be placed with longest edge straight up that level is hard to fill.

Example in Groovy that fails.

int containerW = 100
int containerD = 100
int containerH = 300

def boxes = []
def box

box = new Box(1, 1, 300)
boxes << box
box = new Box(1, 1, 1)
boxes << box

List<Dimension> containers = new ArrayList<Dimension>()
containers.add(Dimension.newInstance(containerW, containerD, containerH))
Packager packager = new Packager(containers)
Container match = packager.pack(boxes)

**Comment by kimmob** [comment]
Found out the reason, the model doesnt suit high containers, will probably rotate the container.

**Comment by skjolber** [comment]
Yeah the largest footprint with the lowest height is selected first, so that is 1x1x1, then only 100x100x299 is left. I'd like to add a brute force approach for such simple cases as this.
