### ISSUE TITLE
This Paper Link is not working.

### ISSUE THREAD

**Issue by komalbb** [skjolber/3d-bin-container-packing#103]
Hi,

The link to LAFF (This Paper) in your documentation is not working. Can you please point me to algorithm paper?

Would you please help me with the following questions as well:
Does the code solve the multiple items trying to go to go multiple containers i.e 3D Multi Bin Packing?

Does the implementation gives provision to control the rotation of the items? My requirement is keep the height axis fixed, No rotation.

How are you using the quantity/weight in determining the fit? My requirement has Volume(length, width, height) as the only attribute of item and bin?

Can you also please provide some examples on how to understand the response (match)?

Thanks

**Comment by skjolber** [comment]
@komalbb  Sorry, the website seems down. Try 

http://webcache.googleusercontent.com/search?q=cache:Fa3PY2ex7hgJ:www.zahidgurbuz.com/yayinlar/An%2520Efficient%2520Algorithm%2520for%25203D%2520Rectangular%2520Box%2520Packing.pdf+&cd=1&hl=no&ct=clnk&gl=no

For the rest, I'll update the docs somewhat, but what you're asking is essentially on the main README?

**Comment by komalbb** [comment]
@skjolber Not specifically on readme, if it is present else where please point it to me?
One more question.
what if the container/bin is partially occupied and we want to fill that with other items? Will the Algo handles the case? If there a way to pass that totalvolume and available volume and items to pack let me know.

**Comment by skjolber** [comment]
There is a section in the readme about rotation? 

No, partially filled is not possible and will not be unless someone contributes that code, as it is not on of my own usecases. See also issue #97.
