### ISSUE TITLE
[Question] Placement check intersect

### ISSUE THREAD

**Issue by hei9gag** [skjolber/3d-bin-container-packing#111]
I have a question about the intersection checking in class Placement.

What is the purpose of the first condition?
```
if (startX <= placement.getSpace().getX() && placement.getSpace().getX() <= endX) {
	return true;
}
```
And why do we need -1 for end value (e.g. endX, endY & endZ)?

Thanks again.

**Comment by skjolber** [comment]
In a single dimension, a box has a start and end coordinate. If one of the coordinates falls within the range of the the other box's start and end coordinate, they intersect. 

I guess this is a part of the code which refined somewhat, but basically it is size vs index inclusive.

**Comment by hei9gag** [comment]
Thanks @skjolber . I wonder if the first condition can be removed. It seems the second condition is doing what you describe above.
```
return startX <= placement.getSpace().getX() + placement.getBox().getWidth() - 1 &&
				placement.getSpace().getX() + placement.getBox().getWidth() - 1 <= endX;
```

**Comment by skjolber** [comment]
But then the first condition cannot be removed, can it; the first coordinate is placement.getSpace().getX() and the second is placement.getSpace().getX() + placement.getBox().getWidth().

**Comment by hei9gag** [comment]
Sorry I mean this condition seems not necessary
```
if (startX <= placement.getSpace().getX() && placement.getSpace().getX() <= endX) {
	return true;
}
```

**Comment by skjolber** [comment]
No, it does not cover all intersects. Do a quick line drawing and you'll see why.
