### ISSUE TITLE
The Level height get from previous highest item height 

### ISSUE THREAD

**Issue by terrychan04** [skjolber/3d-bin-container-packing#123]
I would like to confirm does the Level height get from previous highest box height.

I tried with my testing data in this program compare with real user operation in container packing, i find there is some free space cannot be used.

Would you please see the below?

![cm](https://user-images.githubusercontent.com/51101949/59660559-7945e580-91db-11e9-85e0-f5453cd0c312.png)

**Comment by skjolber** [comment]
Yes, that is the LAFF algorithm. But the packager in this project also tries to use the room above each individual box (B and C, E).
