### ISSUE TITLE
Continue - The Level height get from previous highest item height

### ISSUE THREAD

**Issue by terrychan04** [skjolber/3d-bin-container-packing#126]
Hi skjolber,

I expected it should be like this, but you program seem cannot use the grey area.

![59660559-7945e580-91db-11e9-85e0-f5453cd0c312](https://user-images.githubusercontent.com/51101949/60006687-83685800-96a3-11e9-81d0-254f9b82a88c.png)

**Comment by skjolber** [comment]
@terrychan04 no, it only looks at the space between (height a - height -b) and width of b or c.

**Comment by skjolber** [comment]
See https://github.com/skjolber/3d-bin-container-packing/issues/48

**Comment by terrychan04** [comment]
> @terrychan04 no, it only looks at the space between (height a - height -b) and width of b or c.

May i confirm with you is it like as below?
![60006687-83685800-96a3-11e9-81d0-254f9b82a88c](https://user-images.githubusercontent.com/51101949/60147585-98a6c900-9800-11e9-98cc-eda9a6b654e8.png)

**Comment by skjolber** [comment]
No. Its level by level with use of spare space directly above placed boxes.

**Comment by skjolber** [comment]
@terrychan04 is everything clear now?

**Comment by terrychan04** [comment]
clear, thx..
