### ISSUE TITLE
Stacking for Multiple Layers For 1 column and one layer for 1 column not working

### ISSUE THREAD

**Issue by nitulkukadia** [skjolber/3d-bin-container-packing#13]
Hello @skjolber,

I tried to add test case as below but it failed.

Version Tag: 3d-bin-container-packing-1.0.7
Test Case : LargestAreaFitFirstPackager3DTest.java

       @Test
	public void testStackingMultipleLayersFor3Column() {
		
		List<Box> containers = new ArrayList<Box>();
		containers.add(new Box(30, 10, 6)); // 1800
		LargestAreaFitFirstPackager packager = new LargestAreaFitFirstPackager(containers);
		
		List<BoxItem> products = new ArrayList<BoxItem>();
		
		// 1
		products.add(new BoxItem(new Box("A", 10, 10, 6), 1)); // 600
		// 2 
		products.add(new BoxItem(new Box("D", 10, 10, 2), 3)); // 200 200 200
		Container fits = packager.pack(products);
		assertNotNull(fits);
	}

**Comment by skjolber** [comment]
@nitulkukadia have you read and understood the algorithm? Box 6 and two box D fit in the first level. Then there is no more height left.

**Comment by nitulkukadia** [comment]
Thanks @skjolber 

Can you suggest changes for for abouve case?
I already gone through code to acomodate below case, but it looks difficult.

Container 30*10*6  
Volume is 1800

I have box A with 10*10*6 
Volume 600

Box D 10*10*2
Total 6
Volume 600

So I will put as below in container
____
I  l_l
l  l_l
l_l_l

Long one is with height 6 all other are with 2.
