### ISSUE TITLE
Problem with bin packaging 3D

### ISSUE THREAD

**Issue by vinu481** [skjolber/3d-bin-container-packing#157]
Hi,
I have got 2 bins of dimensions, 145x147x145 and 145x147x145 respectively.
Below are my items with dimensions in the order length x breadth x height
100 x 70 x 90
80 x 75 x 90
60 x 75 x 80
I expect these to be packed in a single bin but 2 of them are packing in one bin and other in a separate bin using LargestAreaFitFirstPackager. 
Is there any parameter to be set before moving further

**Comment by skjolber** [comment]
Well if the first is 100x70x90, it occupies 100x90 of the base area, then non of the others (80x75 and 60x75) will fit in the remaining space (max 57 wide).

**Comment by vinu481** [comment]
This can be achieved by placing the width of the first and 2nd item(70+70=145) against the bin height(145) one above the other. Now there is remaining space above the first item for keeping the 3rd item by placing the length of item against the bin width. Please find the attached image
![1](https://user-images.githubusercontent.com/58232247/69672672-7c010c80-1090-11ea-822a-d7b8ae8344fb.JPG)

**Comment by skjolber** [comment]
Sure, but the LAFF algorithm does not know that. Remeber that algorithms like this really only are searches for solutions, and the LAFF searches a specific subset. 

Have you tried the brute force packager?

**Comment by vinu481** [comment]
No, I haven't tried brute force yet. Does that give the desired solution for this?

**Comment by skjolber** [comment]
You'll have to try it out for yourself. It works level by level as well.

**Comment by skjolber** [comment]
I think it will, guess you'll find out ;-)

**Comment by vinu481** [comment]
Okay I'll check. Thank you 😊

**Comment by LearningByGeek** [comment]
> Okay I'll check. Thank you 😊
How do you finally solve this problem?

**Comment by LearningByGeek** [comment]
> Okay I'll check. Thank you 😊

How do you finally solve this problem?

**Comment by vinu481** [comment]
As per @skjolber , tried the brute force and seems it was working fine. Need to test few more scenarios

**Comment by skjolber** [comment]
@vinu481 thanks for the feedback, how did you make that visualization in the screenshot by the way?

**Comment by vinu481** [comment]
@skjolber It's a free api that provides 3d demonstrations based on the internet. Link follows,
http://packit4me.com/api
