### ISSUE TITLE
Empty spaces not filled

### ISSUE THREAD

**Issue by ZipFerndale** [skjolber/3d-bin-container-packing#159]
My data using only four parts:
Container Size: | length | width | height |  
                          | 100    | 36      | 5 |  
  
Part Num | qty | width | length | height
1                  1     18        90          1
2                  1     18        90          1
3                  1     36         3           1
4                  1     36         3           1

My results:
Placement of '1' is @ (0, 0, 0)
Placement of '2' is @ (0, 18, 0)
Placement of Box '3' is @ (0, 0, 1)
Placement of Box '4' is @ (37, 0, 1)

All parts should fit on single layer

**Comment by skjolber** [comment]
Well the code works as intended, but there is a missing feature: Compare free spaces after placing a box; what are the best two resulting free spaces (in fit2D()).

**Comment by ZipFerndale** [comment]
Will you make the edit?

**Comment by ZipFerndale** [comment]
Or, where in the code should fit2D() fit?

**Comment by skjolber** [comment]
It is going to be compliated / painful. Either somehow try to determine a new 'best space', or, see if the remainder space can be expanded after placing the in the selected ('primary') space.

**Comment by skjolber** [comment]
@ZipFerndale please do a QA of #161
