### ISSUE TITLE
latest versions are not published on maven central

### ISSUE THREAD

**Issue by tyrcho** [skjolber/3d-bin-container-packing#166]
The latest on [mvn central](https://mvnrepository.com/artifact/com.github.skjolber/3d-bin-container-packing) is 1.2.5, what happened to releases up to 1.2.9 ?

**Comment by skjolber** [comment]
Very good question, other libraries, i.e. [csv parser](https://mvnrepository.com/artifact/com.github.skjolber.sesseltjonna-csv/databinder) seem to be published with the same approach.

**Comment by skjolber** [comment]
Packages were renamed given more modules. Use https://mvnrepository.com/artifact/com.github.skjolber.3d-bin-container-packing/core

**Comment by tyrcho** [comment]
@skjolber would you please check about 1.2.10 ? I see it in github releases, but on mvn central

**Comment by skjolber** [comment]
It is just a short delay in their website. Resolving 1.2.10 should work (more or less) straight Sway.

**Comment by tyrcho** [comment]
OK, you were right, sbt (mvn equivalent) managed to download it.
