### ISSUE TITLE
How to get most optimal arrangement when all boxes cannot be placed in a container?

### ISSUE THREAD

**Issue by Vidhin05** [skjolber/3d-bin-container-packing#192]
When it is not possible to pack all the boxes in the container, the code returns NULL, is it possible to get the solution which occupies the most volume in the given container? (Perhaps specifying the boxes not packed)

**Comment by skjolber** [comment]
Not currently, but you can do packaging into multiple containers.

**Comment by Vidhin05** [comment]
@skjolber Is there a way to terminate the algorithm when the container is full and the configuration is saved? Could one achieve this by adding a second box of very big size so we we wouldn't get null and get optimal arrangements for the first package?

**Comment by skjolber** [comment]
No. What is your use-case really?
