### ISSUE TITLE
Stacking too many

### ISSUE THREAD

**Issue by kimmob** [skjolber/3d-bin-container-packing#2]
This test fails.
It should be impossible to stack 17 * 330x88x88 in a 320x490x290 box.

	@Test
	public void testStackThis() {
		List<Box> containers = new ArrayList<Box>();
		containers.add(new Box(320, 490, 290));
		Packager packager = new Packager(containers);

		List<Box> products1 = new ArrayList<Box>();

		products1.add(new Box("01", 330, 88, 88));
		products1.add(new Box("02", 330, 88, 88));
		products1.add(new Box("03", 330, 88, 88));
		products1.add(new Box("04", 330, 88, 88));
		products1.add(new Box("05", 330, 88, 88));
		products1.add(new Box("06", 330, 88, 88));
		products1.add(new Box("07", 330, 88, 88));
		products1.add(new Box("08", 330, 88, 88));
		products1.add(new Box("09", 330, 88, 88));
		products1.add(new Box("10", 330, 88, 88));
		products1.add(new Box("11", 330, 88, 88));
		products1.add(new Box("12", 330, 88, 88));
		products1.add(new Box("13", 330, 88, 88));
		products1.add(new Box("14", 330, 88, 88));
		products1.add(new Box("15", 330, 88, 88));
		products1.add(new Box("16", 330, 88, 88));
		products1.add(new Box("17", 330, 88, 88));

		Container fits1 = packager.pack(products1);
		assertNull(fits1);

	}

**Comment by skjolber** [comment]
I've commited a fix, please verify that it is working as expected.

**Comment by kimmob** [comment]
Great, but I think it still packs too many. I did an simpler test here. Since 38 > 36 I think it's quite obvious only 3 products fit side to side.

	@Test
	public void testIssue2_part2() {
		List<Box> containers = new ArrayList<Box>();
		containers.add(new Box(36, 55, 13));
		Packager packager = new Packager(containers);

		List<Box> products1 = new ArrayList<Box>();

		products1.add(new Box("01", 38, 10, 10));
		products1.add(new Box("02", 38, 10, 10));
		products1.add(new Box("03", 38, 10, 10));
		products1.add(new Box("04", 38, 10, 10));

		Container fits1 = packager.pack(products1);
		assertNull(fits1);
	}

**Comment by skjolber** [comment]
Right, try now.

**Comment by kimmob** [comment]
Perfect, didnt find any new problems.
