### ISSUE TITLE
Possible bug - does container's volume order matters?

### ISSUE THREAD

**Issue by clgraf** [skjolber/3d-bin-container-packing#208]
Hi there, testing your code I've noticed that the container's volume order makes diference in the result. Follow a snip that reproduces the issue. It should fit the items in a big box and a small box

    public void testDescendingOrder() { // it fails
        List<Container> containers = new ArrayList<Container>();
        containers.add(new Container("BigBox", 400, 400, 400, 10000));
        containers.add(new Container("SmallBox", 200, 200, 200, 10000));
        Packager packager = LargestAreaFitFirstPackager.newBuilder().withContainers(containers).build();
        List<BoxItem> products = new ArrayList<BoxItem>();
        products.add(new BoxItem(new Box("Foot", 200, 200, 200, 1000), 2));
        products.add(new BoxItem(new Box("Leg", 200, 200, 200, 1000), 7));
        List<Container> fits = packager.packList(products, 999, System.currentTimeMillis() + 5000);
        Assert.assertEquals("It should be a big box", fits.get(0).getName(), "BigBox"); // ok
        Assert.assertEquals("It should be a small box", fits.get(1).getName(), "SmallBox"); // fails
    }

Thank you!!

**Comment by skjolber** [comment]
The container order is important. The packager uses the order as a priority; picking the first over the seconds if they both can hold the same number of boxes.

Just reversing the container order makes the test-case pass.
