### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by torsakch** [skjolber/3d-bin-container-packing#234]
I've plot the box from matplotlib and got this image. So I doubt that the box is placed in the air!! So is this bug and why it placed the box like that? Thank you

<img width="667" alt="Screen Shot 2020-09-28 at 11 22 05 PM" src="https://user-images.githubusercontent.com/811099/94459361-6e04a680-01e1-11eb-9341-3ae2f1692195.png">

**Comment by torsakch** [comment]
`// initialization
    List<Container> containers = new ArrayList<Container>();
    containers.add(new Container(10, 30, 10, 1000));
  
    Packager packager = new BruteForcePackager(containers, false, true, 1);

    List<BoxItem> products = new ArrayList<BoxItem>();
    products.add(new BoxItem(new Box("Box1", 4, 3, 2, 25), 4));
    products.add(new BoxItem(new Box("Box2", 4, 5, 3, 25), 5));
    products.add(new BoxItem(new Box("Box3", 4, 3, 4, 50), 6));

    int maxContainers = 10; 
      List<Container> matchList = packager.packList(products, maxContainers, Long.MAX_VALUE);  
`

**Comment by skjolber** [comment]
Yes, that is possible with the current implementation. Have you studied the LAFF algorithm?

**Comment by torsakch** [comment]
> Yes, that is possible with the current implementation. Have you studied the LAFF algorithm?

How to get rid of this situation? Do you have recommendation or suggestion?  I've just read the algorithm in the readme file. Thank you.

**Comment by skjolber** [comment]
Open another issue when you've studied the LAFF algorithm.
