### ISSUE TITLE
3d rotation not enabled by default in builder

### ISSUE THREAD

**Issue by jotoh98** [skjolber/3d-bin-container-packing#251]
AS mentioned in the readme, the 3d rotation should be enabled by default in the LAFF-algorithm. But using the builder pattern, the flag LargestAreaFitFirstPackagerBuilder#rotate3D is set to false through the [default initialization](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html).

This or the readme should be changed to prevent confusion.

**Comment by skjolber** [comment]
@jotoh98 thanks for the bug report and PR, released as version `1.2.13`.

**Comment by itsalongstory** [comment]
Still unfixed?

```xml
<dependency>
    <groupId>com.github.skjolber.3d-bin-container-packing</groupId>
    <artifactId>core</artifactId>
    <version>1.2.13</version>
</dependency>
```

```java
List<Container> containers = new ArrayList<Container>();
containers.add(new Container("c1",1400, 1000, 1000, 0));
Packager packager = LargestAreaFitFirstPackager.newBuilder().withContainers(containers).build();

List<BoxItem> products = new ArrayList<BoxItem>();
products.add(new BoxItem(new Box("b1", 980, 950, 590, 0), 2));

List<Container> fits = packager.packList(products, 99999, System.currentTimeMillis() + 10000);

System.out.println(fits);
```

output 2 containers, but 1 container is enough

```
[
  Container [stackWeight=0, stackHeight=0, levels=[[Placement [b1 0x0x0, width=980, depth=950, height=590]]], weight=0, width=1400, depth=1000, height=1000, volume=1400000000, name=c1],
  Container [stackWeight=0, stackHeight=0, levels=[[Placement [b1 0x0x0, width=980, depth=950, height=590]]], weight=0, width=1400, depth=1000, height=1000, volume=1400000000, name=c1]
]
```

**Comment by skjolber** [comment]
Is this the same issue? The LAFF packager will not find all optimal solutions.

**Comment by itsalongstory** [comment]
> Is this the same issue? The LAFF packager will not find all optimal solutions.

```java
containers.addAll(new Container("c1",1400, 1000, 1000, 0).rotations());
```

`container.rotations()` fixed this. Want to know why container doesn't rotate automatically.
