### ISSUE TITLE
Error placements

### ISSUE THREAD

**Issue by gargolillas** [skjolber/3d-bin-container-packing#260]
In this example the best packing is product A,B,D in the first level and product C in the second level. But it pack C,D in the first level and A,B in the second level. 
If I extract product 'C' then can bin all products (A, B and D) in the first level (option 3Drotate = false):
                
                List<Container> containers = new ArrayList<>();
		containers.add(new Container(128, 55, 244, 0));
		
		LargestAreaFitFirstPackager packager = new LargestAreaFitFirstPackager(containers);

		List<BoxItem> products = new ArrayList<>();

		products.add(new BoxItem(new Box("A", 52, 54, 125, 0), 1));
		products.add(new BoxItem(new Box("B", 26, 54, 106, 0), 1));
		products.add(new BoxItem(new Box("C", 64, 54, 105, 0), 1));
		products.add(new BoxItem(new Box("D", 32, 54, 105, 0), 1));

		List<Container> fits = packager.packList(products, Integer.MAX_VALUE, Long.MAX_VALUE);

**Comment by skjolber** [comment]
Yeah, that is totally as expected. The algorithm is not that intelligent really, it is more like a search in a subset of the possible placements.
