### ISSUE TITLE
More usage examples?

### ISSUE THREAD

**Issue by gerroon** [skjolber/3d-bin-container-packing#261]
Hi

Is it possible to get more usage examples maybe a bit more detailed steps to how add and calculate the content? The lines in the readme is very minimal and does not give a sense of what cna be done with the library.

thanks

**Comment by skjolber** [comment]
Yeah, what is really needed is a good graphical representation of the resulting packaging, which supports incremental results, so that the algorithm is visualized better.

**Comment by skjolber** [comment]
A basic visualizer was added. 

See the unit tests for more examples.
