### ISSUE TITLE
 Support for Bigdecimal data type

### ISSUE THREAD

**Issue by palomasalas** [skjolber/3d-bin-container-packing#267]
I take this opportunity to give a cordial greeting. First of all I appreciate the work of the project. It is easy to understand and implement. I want to ask if it will be possible to have the BigDecimal data type to consider the Dimension and Box. 

I appreciate the attention

**Comment by skjolber** [comment]
What is your use-case? Any decimal will be inaccurate, which is not a good thing when trying to stash things together with zero distance between.

**Comment by palomasalas** [comment]
Thanks for the attention, I already solved the case.
