### ISSUE TITLE
Problems getting BruteForcePackager to work on example

### ISSUE THREAD

**Issue by c2rosa** [skjolber/3d-bin-container-packing#28]
I am calling:

Packager myPackager = new BruteForcePackager(containers, rotate3d, binarySearch);

where 
                boolean rotate3d = false;
                boolean binarySearch = true;

and 
List<Dimension> containers = new ArrayList<Dimension>();

and 
containers.add(Dimension.newInstance(294, 46, 94));

I then call:
                    long deadline = System.currentTimeMillis() + 70000;
                    match = myPackager.pack(piecesToPutInContainer, deadline);

where
List<BoxItem> piecesToPutInContainer = new ArrayList<BoxItem>();
and

piecesToPutInContainer has size 2
and

piecesToPutInContainer.get(0) has
count=2
and
box = Box [name=null, width=98, depth=45, height=28, volume=123480]

and

piecesToPutInContainer.get(1) has
count=2
and
box = Box [name=null, width=98, depth=45, height=93, volume=410130]

These 4 pieces in total shouldfit in the container above....and yet the BruteForcePackager object returns
Container match = null

which I interpret to mean that the algorithm couldn't find a way to fit these in.

Why doesn't it find a solution?

Thanks for your help with this.

Best regards, Charlie

**Comment by skjolber** [comment]
Hi, can you submit a PR with the (failing) unit test of the above?

**Comment by tyrcho** [comment]
I've created #30 with a unit test for my situation in which BruteForcePackage fails to find an "obvious" solution with 6 packets.

I have 6 similar packets (each dimensions differs from less than 5 from a reference one) and a container large enough (3x2 blocks with the largest packet).

An online API confirms that this problem has a solution, displayed in this image
![](https://eu.api.3dbinpacking.com/images/70355d43d0ac5bf8af5fbb647c0b4186/20180809/b0555e3071e69b68bb03d2ea98ec5e96/1533807790-4544-9208123.png)

**Comment by skjolber** [comment]
@tyrcho thanks for the bug report and a good unit test. The issue has been fixed in the 'multiple' branch. 

https://github.com/skjolber/3d-bin-container-packing/blob/multiple/src/main/java/com/github/skjolberg/packing/BruteForcePackager.java#L194

Basically since the brute force algorithm has no logic for selection of a 'fitting' box, it does not make sense to limit the height of the current level by the first box.

**Comment by tyrcho** [comment]
cool, good news ! Any idea when this fix will be released on Maven Central ? I'd appreciate a new release in the next days is possible at all.

**Comment by skjolber** [comment]
@tyrcho sure, I've just released version 1.0.8 - guess it will propagate to the relevant servers within a few hours or a day.
