### ISSUE TITLE
BruteForcePackager produces invalid packing (items intersect)

### ISSUE THREAD

**Issue by J-M-Barnes** [skjolber/3d-bin-container-packing#297]
I've encountered an input on which `BruteForcePackager` seems to produce a "false positive" (items do not fit in the container, but `BruteForcePackager` says they do):

```java
List<Container> containers = new ArrayList<Container>();
containers.add(new Container(282, 222, 190, 9));
Packager packager = BruteForcePackager.newBuilder().withContainers(containers).build();

List<BoxItem> products = new ArrayList<BoxItem>();
products.add(new BoxItem(new Box("A", 213, 187, 180, 1), 1));
products.add(new BoxItem(new Box("B", 217, 170, 78, 1), 1));
products.add(new BoxItem(new Box("C", 129, 102, 71, 1), 1));

Container match = packager.pack(products);
System.out.println(match);
```

The packager _should_ return null, as the three items cannot physically fit in the container. But instead the output is:

```
Container [stackWeight=0, stackHeight=0, levels=[[Placement [C 0x0x0, width=71, depth=129, height=102], Placement [A 71x0x0, width=180, depth=213, height=187], Placement [B 0x0x102, width=217, depth=170, height=78]]], weight=9, width=282, depth=222, height=190, volume=11894760, name=null]
```

If you sketch the placements in the output, you can see that they are invalid; boxes A and B overlap.

![sketch](https://user-images.githubusercontent.com/33334327/117212256-f8803a80-adae-11eb-825f-34aaedb0f017.png)

Let me know if I'm doing something wrong or misunderstanding what I'm seeing. (But these inputs are based on physical items I have, and the items pretty clearly do not physically fit in the box, so it does seem like this result is wrong.) This is on version 1.2.13.

**Comment by skjolber** [comment]
Release fix
