### ISSUE TITLE
FEAT: compute actually used space

### ISSUE THREAD

**Issue by tyrcho** [skjolber/3d-bin-container-packing#31]
Hi,

In my usage of the library, I've encounter the need to get the space actually used by the objects packed in the container. (as the smallest container which can hold the items)

I managed to do it, but it's non trivial because height is processed differently than the other 2 dimensions.

Would you agree to have this as a method `Container.getUsedSpace` returning a `Dimension` ?

**Comment by skjolber** [comment]
So basically you'd want the bounding box (as a Dimension) of the Levels (as sum of Placements) within the container? Like for example to calculate how much padding there would be room for inside a Container? 

My scala is not that great, so go ahead and submit a PR, this sounds like a trivial change so should be possible to resolve within a short timeframe.

**Comment by tyrcho** [comment]
exactly !
sure, I'll try to submit the PR today

**Comment by skjolber** [comment]
1.0.9 is submitted to the maven central repo, but probably there will be a delay before its propagated everywhere, so your milage will vary.

**Comment by tyrcho** [comment]
thanks for the 1.0.9 ! I've used it successfully in my project.
