### ISSUE TITLE
refactoring : reduce visibility of implementation details

### ISSUE THREAD

**Issue by tyrcho** [skjolber/3d-bin-container-packing#34]
While working on the project, I noticed that a lot of details are exposed to classes which depend on this API.

I suggest to hide the implementation details in a separate package with lower visibility and only keep the really useful in the main package.

Something like

- `com.github.skjolberg.packing` with public classes
  * `Packager`
  * `Dimension`, `BoxItem`
- `com.github.skjolberg.packing.impl` with package-protected classes
  * maybe `Level`, `Placement` can be moved here
  * `BruteForcePackager`, `LAFFPackager` (with a Factory in the public package)

What do you think ? Would you like another PR with these changes ?

**Comment by skjolber** [comment]
I guess you have a valid point, however I'd like to merge 

https://github.com/skjolber/3d-bin-container-packing/pull/14

before doing any refactorings - there will be merge/conflict hell.

**Comment by tyrcho** [comment]
sure ! ping me here when you feel the time is right

**Comment by skjolber** [comment]
Merged https://github.com/skjolber/3d-bin-container-packing/pull/47.
