### ISSUE TITLE
BruteForcePackager or ParallelBruteForcePackager randomly throw IllegalArgumentException

### ISSUE THREAD

**Issue by functionportal** [skjolber/3d-bin-container-packing#385]
When packing using BruteForcePackager and ParallelBruteForcePackager item count of 6 items the Packages.pack(boxItems, deadline) call results in an IllegalArgumentException:

java.lang.IllegalArgumentException: Remaining free space is negative at -220 for Container [stackWeight=98, stackHeight=410, levels=[[Placement [null 0x0x0, width=410, depth=150, height=410], Placement [null 0x150x0, width=410, depth=150, height=410], Placement [null 0x300x0, width=450, depth=255, height=255]]], weight=2147483647, width=600, depth=600, height=600, volume=216000000, name=null]

This exception is thrown randomly, and in some cases executes successfully with items fitting in the container. Deadline is not a factor, since when the exception is thrown, it's thrown instantly.

**Comment by suchwerk** [comment]
Could you provide a test/reproducer?
