### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by dmitryrudenko** [skjolber/3d-bin-container-packing#4]
Input:

Packager packager = new Packager(ImmutableList.of(new Dimension("Plane", 1335, 285, 247)), false);
List<Box> products = new ArrayList<>();
products.add("72407",20,30,15);
products.add("74809",100,120,52);
products.add("71535",30,40,15);
products.add("74780",20,30,15);
products.add("74760_1",30,20,15);
products.add("74760_2",30,20,15);
products.add("74757",30,40,15);
products.add("74808",100,120,75);
products.add("73770",20,30,15);
products.add("74844_1",60,40,28);
products.add("74844_2",60,40,28);
products.add("74844_3",60,40,28);
products.add("74846",30,40,15);
products.add("73767_1",60,50,15);
products.add("73767_2",60,50,15);
products.add("74848",20,30,15);
products.add("74850",20,30,15);
products.add("74852",20,30,15);
products.add("74787",100,120,154);
products.add("74806_1",30,20,15);
products.add("74806_2",30,20,15);
products.add("74806_3",30,20,15);
products.add("74806_4",30,20,15);
products.add("74806_5",30,20,15);
products.add("74806_6",30,20,15);
products.add("74806_7",30,20,15);
products.add("74806_8",30,20,15);
products.add("74806_9",30,20,15);
products.add("74781_1",30,20,15);
products.add("74781_2",30,20,15);
products.add("74781_3",30,20,15);
products.add("74775_1",30,20,15);
products.add("74775_2",30,20,15);
products.add("74775_3",30,20,15);
products.add("74775_4",30,20,15);
products.add("74756",100,120,75);
products.add("74797",30,40,15);
products.add("74835",100,120,133);
products.add("74834",100,120,36);
products.add("74833",100,120,30);
products.add("74784_1",30,20,15);
products.add("74784_2",30,20,15);
products.add("74782",100,120,50);
products.add("74765",30,40,15);
products.add("74769",12,30,15);
products.add("74802",80,120,35);
products.add("73769",20,30,15);
products.add("74799_1",40,30,15);
products.add("74799_2",40,30,15);
products.add("74799_3",40,30,15);
products.add("74799_4",40,30,15);
products.add("74799_5",40,30,15);
products.add("74799_6",40,30,15);
products.add("74827",100,120,125);
products.add("74800_1",60,40,28);
products.add("74800_2",60,40,28);
products.add("74800_3",60,40,28);
products.add("74800_4",60,40,28);
products.add("74800_5",60,40,28);
products.add("74800_6",60,40,28);
products.add("74800_7",60,40,28);
products.add("74823",100,120,129);
products.add("74853",20,30,15);
products.add("74839_1",120,100,130);
products.add("74839_2",120,100,130);
products.add("74839_3",120,100,130);
products.add("74849_1",120,100,127);
products.add("74849_2",120,100,127);
products.add("74777_1",120,100,35);
products.add("74777_2",120,100,35);
products.add("72583",60,114,64);
products.add("74737",100,120,116);
products.add("74774_1",121,101,54);
products.add("74774_2",121,101,54);
products.add("74774_3",121,101,54);
products.add("74772",100,120,130);
products.add("72434",20,30,15);
products.add("74831",100,120,129);
products.add("74832",30,40,15);
products.add("74778_1",120,100,101);
products.add("74778_2",120,100,101);
products.add("74778_3",120,100,101);
products.add("74778_4",120,100,101);
products.add("74845_1",115,60,65);
products.add("74845_2",115,60,65);
products.add("74776_1",120,100,128);
products.add("74776_2",120,100,128);
products.add("72385",20,30,15);
products.add("74779_1",120,100,36);
products.add("74779_2",120,100,36);
products.add("74779_3",120,100,36);
products.add("74779_4",120,100,36);
products.add("72422",50,60,15);
products.add("BRE72563_1",40,30,15);
products.add("BRE72563_2",40,30,15);
products.add("BRE72563_3",40,30,15);
products.add("BRE72563_4",40,30,15);
products.add("72578",100,120,75);
products.add("71555",100,120,52);
products.add("74830_1",40,30,15);
products.add("74830_2",40,30,15);
products.add("74816",100,120,48);

final Container pack = packager.pack(products);

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException
	at com.github.skjolberg.packing.Container.getRemainigFreeSpace(Container.java:52)
	at com.github.skjolberg.packing.Packager.pack(Packager.java:73)

**Comment by skjolber** [comment]
Fixed in lastest master
