### ISSUE TITLE
Version 2.0.0 QA and performance improvements

### ISSUE THREAD

**Issue by skjolber** [skjolber/3d-bin-container-packing#403]
* delete unused code, if any :heavy_check_mark:
 * add more unit tests and documentation
      * use item-generator in more tests
 * optimize execution runtime
      * more JMH tests :heavy_check_mark:
      * Improve extreme-points :heavy_check_mark:
      * remove extreme-points which volume is not big enough to store anything :heavy_check_mark:
      * correlate boxes of equal side
 * create issues for additional functionality
      * additions for a working max weight / max stack height unit test to succeed
      * TBD
 * better CI
    * set up code coverage
    * more badges

**Comment by tyrcho** [comment]
I suggest you add some Property-Based Tests, these are what helped me catch the regressions from 1.X to 2.X

Here is an old presentation I made on the subject : https://tyrcho.github.io/pbt-kata/#15

And the java framework which we can use in this project : https://github.com/pholser/junit-quickcheck

Do you need help ?

I could port some examples I use to test your library from the scala world

**Comment by skjolber** [comment]
Thanks, I'll have a look at the property-based testing. If you have some "high-level" tests available, then that is great. 

Seems with 2.x some of the fundamental work has been done, but the actual logic of the packagers is still pretty crude.

**Comment by tyrcho** [comment]
I just started the setup in #483 , I'll try to provide some more interesting samples later on

**Comment by skjolber** [comment]
@tyrcho looks like a promising start! I have and been super busy with other projects, so great to get some tests up and running. I still feel like some more functionality is necessary, so (reasonably) high-level tests are the best.
