### ISSUE TITLE
How to run this project for test?

### ISSUE THREAD

**Issue by MONO-ON** [skjolber/3d-bin-container-packing#449]
I found it while looking for open sources because I will in charge of container loading project.

However, I have no experience with Java and Maven.

I tried "npm run start" in the viewer directory, but nothing show up.

Where should I put the data and which command should I use?

<img width="2096" alt="image" src="https://user-images.githubusercontent.com/37432366/155355392-0230d159-6d75-4e9d-8433-17da200d05c2.png">

 -> Result Image when I ran. (left : I ran "mvn test" right: "npm run start")

<img width="2507" alt="image" src="https://user-images.githubusercontent.com/37432366/155355089-ab43043d-eac1-42b6-8c34-8113fa996603.png">

**Comment by MONO-ON** [comment]
> I found it while looking for open sources because I will in charge of container loading project.
> 
> However, I have no experience with Java and Maven.
> 
> I tried "npm run start" in the viewer directory, but nothing show up.
> 
> Where should I put the data and which command should I use?

**Comment by skjolber** [comment]
@MONO-ON make your unit tests write to a file within the viewer, i.e. run one of the tests [here](https://github.com/skjolber/3d-bin-container-packing/blob/master/visualizer/packaging/src/test/java/com/github/skjolber/packing/visualizer/packaging/VisualizationTest.java)

**Comment by skjolber** [comment]
(Those tests are skipped by maven)

**Comment by skjolber** [comment]
(Those tests are skipped by maven)
