### ISSUE TITLE
Wrong placement of boxes within a level with 2d rotation turned on

### ISSUE THREAD

**Issue by dmitryrudenko** [skjolber/3d-bin-container-packing#5]
Before running change 
currentBox.getHeight() > box.getHeight()  to -> currentBox.getHeight() < box.getHeight()
in Packager::88 (otherwise it won't fit all this stuff)

Images show placement of boxes, black dot is box center. Obviously some of the boxes intersect

Code to test.

java.util.List<Box> containers = new ArrayList<Box>();
containers.add(new Box("Plane", 1355, 285, 247));
Packager packager = new Packager(containers, false);
List<Box> products = new ArrayList<Box>();
products.add(new Box("72407",20,30,15));
products.add(new Box("74809",100,120,52));
products.add(new Box("71535",30,40,15));
products.add(new Box("74780",20,30,15));
products.add(new Box("74760_1",30,20,15));
products.add(new Box("74760_2",30,20,15));
products.add(new Box("74757",30,40,15));
products.add(new Box("74808",100,120,75));
products.add(new Box("73770",20,30,15));
products.add(new Box("74844_1",60,40,28));
products.add(new Box("74844_2",60,40,28));
products.add(new Box("74844_3",60,40,28));
products.add(new Box("74846",30,40,15));
products.add(new Box("73767_1",60,50,15));
products.add(new Box("73767_2",60,50,15));
products.add(new Box("74848",20,30,15));
products.add(new Box("74850",20,30,15));
products.add(new Box("74852",20,30,15));
products.add(new Box("74787",100,120,154));
products.add(new Box("74806_1",30,20,15));
products.add(new Box("74806_2",30,20,15));
products.add(new Box("74806_3",30,20,15));
products.add(new Box("74806_4",30,20,15));
products.add(new Box("74806_5",30,20,15));
products.add(new Box("74806_6",30,20,15));
products.add(new Box("74806_7",30,20,15));
products.add(new Box("74806_8",30,20,15));
products.add(new Box("74806_9",30,20,15));
products.add(new Box("74781_1",30,20,15));
products.add(new Box("74781_2",30,20,15));
products.add(new Box("74781_3",30,20,15));
products.add(new Box("74775_1",30,20,15));
products.add(new Box("74775_2",30,20,15));
products.add(new Box("74775_3",30,20,15));
products.add(new Box("74775_4",30,20,15));
products.add(new Box("74756",100,120,75));
products.add(new Box("74797",30,40,15));
products.add(new Box("74835",100,120,133));
products.add(new Box("74834",100,120,36));
products.add(new Box("74833",100,120,30));
products.add(new Box("74784_1",30,20,15));
products.add(new Box("74784_2",30,20,15));
products.add(new Box("74782",100,120,50));
products.add(new Box("74765",30,40,15));
products.add(new Box("74769",12,30,15));
products.add(new Box("74802",80,120,35));
products.add(new Box("73769",20,30,15));
products.add(new Box("74799_1",40,30,15));
products.add(new Box("74799_2",40,30,15));
products.add(new Box("74799_3",40,30,15));
products.add(new Box("74799_4",40,30,15));
products.add(new Box("74799_5",40,30,15));
products.add(new Box("74799_6",40,30,15));
products.add(new Box("74827",100,120,125));
products.add(new Box("74800_1",60,40,28));
products.add(new Box("74800_2",60,40,28));
products.add(new Box("74800_3",60,40,28));
products.add(new Box("74800_4",60,40,28));
products.add(new Box("74800_5",60,40,28));
products.add(new Box("74800_6",60,40,28));
products.add(new Box("74800_7",60,40,28));
products.add(new Box("74823",100,120,129));
products.add(new Box("74853",20,30,15));
products.add(new Box("74839_1",120,100,130));
products.add(new Box("74839_2",120,100,130));
products.add(new Box("74839_3",120,100,130));
products.add(new Box("74849_1",120,100,127));
products.add(new Box("74849_2",120,100,127));
products.add(new Box("74777_1",120,100,35));
products.add(new Box("74777_2",120,100,35));
products.add(new Box("72583",60,114,64));
products.add(new Box("74737",100,120,116));
products.add(new Box("74774_1",121,101,54));
products.add(new Box("74774_2",121,101,54));
products.add(new Box("74774_3",121,101,54));
products.add(new Box("74772",100,120,130));
products.add(new Box("72434",20,30,15));
products.add(new Box("74831",100,120,129));
products.add(new Box("74832",30,40,15));
products.add(new Box("74778_1",120,100,101));
products.add(new Box("74778_2",120,100,101));
products.add(new Box("74778_3",120,100,101));
products.add(new Box("74778_4",120,100,101));
products.add(new Box("74845_1",115,60,65));
products.add(new Box("74845_2",115,60,65));
products.add(new Box("74776_1",120,100,128));
products.add(new Box("74776_2",120,100,128));
products.add(new Box("72385",20,30,15));
products.add(new Box("74779_1",120,100,36));
products.add(new Box("74779_2",120,100,36));
products.add(new Box("74779_3",120,100,36));
products.add(new Box("74779_4",120,100,36));
products.add(new Box("72422",50,60,15));
products.add(new Box("BRE72563_1",40,30,15));
products.add(new Box("BRE72563_2",40,30,15));
products.add(new Box("BRE72563_3",40,30,15));
products.add(new Box("BRE72563_4",40,30,15));
products.add(new Box("72578",100,120,75));
products.add(new Box("71555",100,120,52));
products.add(new Box("74830_1",40,30,15));
products.add(new Box("74830_2",40,30,15));
products.add(new Box("74816",100,120,48));

Container pack = packager.pack(products);
![saved1](https://user-images.githubusercontent.com/5985574/31241220-ee7c1fae-aa0b-11e7-974b-fd679b5fa1ac.png)
![saved2](https://user-images.githubusercontent.com/5985574/31241221-ee7d5810-aa0b-11e7-8610-119c3a7a238f.png)

**Comment by skjolber** [comment]
Please verify fix in

https://github.com/skjolber/3d-bin-container-packing/pull/6

**Comment by dmitryrudenko** [comment]
Works for me, thank you

**Comment by dmitryrudenko** [comment]
![saved1](https://user-images.githubusercontent.com/5985574/31245422-f6b6db6c-aa12-11e7-9ff5-be30f4975def.png)
![saved2](https://user-images.githubusercontent.com/5985574/31245423-f723bb6a-aa12-11e7-9ccb-bd4fdb61c1de.png)
