### ISSUE TITLE
Bug in the BruteForcePackager

### ISSUE THREAD

**Issue by claire-mielcarek** [skjolber/3d-bin-container-packing#503]
We found some scenario in which the BruteForcePackager fails unexpectedly. 

Using the version 1.2.14 of you library, the packager regularly throws an `IllegalArgumentException` with message `Remaining free space is negative at -1220 for Container [stackWeight=0, stackHeight=1360, levels=[[Placement [E 0x0x0, width=930, depth=1900, height=1360]]], weight=0, width=1000, depth=2000, height=1500, volume=3000000000, name=container1]`. 

This [PR](https://github.com/skjolber/3d-bin-container-packing/pull/502) presents an example of said scenarios. The test should succeed, but fails by throwing an exception.

**Comment by skjolber** [comment]
@claire-mielcarek your PR does not throw that exception on the 1.x branch. Do you have more examples?

**Comment by skjolber** [comment]
@claire-mielcarek ok, I confirm it is a bug

**Comment by skjolber** [comment]
@claire-mielcarek please run your tests against the latest code in the 1.x branch

**Comment by claire-mielcarek** [comment]
Wonderful, it pass now !

**Comment by tyrcho** [comment]
Hmm by pure chance I found that the PBT still reproduces this bug : #505 

I've tried to reproduce it on a simple test case with `testForIllegalArgumentException` but the test passes.

However `identicalBoxesShouldFitInContainers` when run enough times (100 is enough for me) reproduces the bug.
