### ISSUE TITLE
How to define container and Stackable with Double dimentions

### ISSUE THREAD

**Issue by NguyenMinh1912** [skjolber/3d-bin-container-packing#506]
My products has double dimentions but no i can't not find any solution for this
I want to define some thing like this
Container container8 = Container.newBuilder()
              .withDescription("1")
              .withSize(22.2, 22.2, 12.2)
              .withEmptyWeight(1)
              .withMaxLoadWeight(100)
              .build();

new StackableItem(Box.newBuilder().withId("Arm").withSize(4.5, 10.5, 2.3).withRotate3D().withWeight(50).build(), 1);
I remenber the older version support this issue? 
I want to packed mini order so use Math.round() is expensive picker carton approach

**Comment by skjolber** [comment]
Add a converter. 22.2 -> 222 and back again after stacking.
