### ISSUE TITLE
Container load volume integer overflow

### ISSUE THREAD

**Issue by obstrom** [skjolber/3d-bin-container-packing#512]
Hi, thanks for this library!

Working with Containers with large dimensions I'm having the issue that the `getFreeVolumeLoad()` method on the Container class produces negative values.

After stepping through the code it seems to be due to the method `getVolume()` in `DefaultStack.java` summing the volume values of all `StackPlacement` objects from `long` values to `int` causing the sum to possibly wrap-around if it overflows the integer.

_From getVolume() method in DefaultStack.java, with my comments to highlight the issue_
```
int volume = 0; // should be a long?

for (StackPlacement stackEntry : entries) {
	volume += stackEntry.getStackable().getVolume(); // returns a long and attempts to add it to an integer
}
```

**Comment by skjolber** [comment]
@obstrom thanks for the bug report, fixed released as 2.0.10.
