### ISSUE TITLE
StackConstraint on LargestAreaFitFirstPackager supports() method and the z value

### ISSUE THREAD

**Issue by othp** [skjolber/3d-bin-container-packing#528]
Using a 2.0.8 build for my project I set up a StackConstraint on a container with the goal of being able to support packing items into a container with an open top where items could be stacked such that they poked out the open top of the container as long as the bottom of the item was still actually in the box - so it would be ok for a big item to sit in the container with part of it sticking out the top but it wouldn't be ok to pack two items with the same combined height as that big item if the second item was stacked on the first such that it's bottom z value exceeded the height of the container (or didn't have some amount of overlap) since it could slide off and fall out while the container was being moved. 

In order to achieve this I set the height of the container to be more than it really physically was and then rejected boxes that were stacked too high using a StackConstraint. This works fine, but I had to hack around a discrepancy between how the LargestAreaFitFirstPackager and the BruteForcePackager passed the z value to the supports method. While the BruteForcePackager did what I expected and passed z as the actual z of the box, the LargestAreaFitFirstPackager would pass a z value relative to the current level in the LevelStack and not the absolute z. This was quite confusing, and getting at the actual level offset was non-trivial. This is what I ended up with that seems to work:
```
	int levelOffset = 0;
	if (stack instanceof LevelStack) {
		boolean isFirst = x == 0 && y == 0 && z == 0;
		LevelStack levelStack = (LevelStack) stack;
		List<Stack> levels = levelStack.getLevels();
		Stack lastLevel = null;
		if (isFirst) {
			if (levels.size() > 0) {
				lastLevel = levels.get(levels.size() - 1);
			}
		} else {
			if (levels.size() > 1) {
				lastLevel = levels.get(levels.size() - 2);
			}
		}

		if (lastLevel != null) {
			List<StackPlacement> placements = lastLevel.getPlacements();
			if (placements.size() > 0) {
				StackPlacement placement = lastLevel.getPlacements().get(0);
				levelOffset = placement.getAbsoluteEndZ() + 1;
			}
		}
	}
```
Since this is based on the internals of the packing algorithm I'm worried it will break next time I upgrade. Can we make it so the supports call is passed a consistent z value for all of the packers?

**Comment by skjolber** [comment]
@othp interesting usecase. I agree the passed z offset should not have two meanings. The whole `StackConstraint` could be improved.

**Comment by skjolber** [comment]
@othp does this https://github.com/skjolber/3d-bin-container-packing/pull/531 update solve it?

**Comment by skjolber** [comment]
I assume yes.
