### ISSUE TITLE
Is there a way to access the list of items that were placed in each packed box?

### ISSUE THREAD

**Issue by mlin-chwy** [skjolber/3d-bin-container-packing#548]
I've imported this repo into my project as an external library, and I have just gotten it to pack multiple boxes. However, I can't find a way to get the list of items that the algorithm has chosen to place in each box, and I was wanting to return this information in my program. How can I access this information/is it stored in a particular field? Thanks!

**Comment by skjolber** [comment]
Container: get the `Stack` and then the `StackPlacement` and then the `Stackable`.
