### ISSUE TITLE
Dimension should support float/double value instead of int

### ISSUE THREAD

**Issue by sk-space** [skjolber/3d-bin-container-packing#558]
The box dimensions measured should support double or floating point value instead of integer. Providing double/float value will be more generic in terms of usability.
Expected result:
`AbstractContainerBuilder` with method `withSize(double dx, double dy, double dz)`,
 where the class variables `dx`, `dy` and `dz` all should be in decimal format number.

**Comment by skjolber** [comment]
The user is expected to factor in the precison of his own measurements in the input `dx / dy / dz`. Make a wrapper if you prefer desimal (cm?) units.
