### ISSUE TITLE
Sorting order issue

### ISSUE THREAD

**Issue by souravdalal** [skjolber/3d-bin-container-packing#588]
Hi,
It seems the StackableItems needs to be sorted first before putting into container list. Can you please provide the sort order needs to be used. Please check the below code. If I provide the container is Arrays.asList with container order 1,2,3,4,5 then it gives me right dimension (2/4/6); but if use 2,1,5,4,3 then it gives me dimension (4/4/6)

              Container container1 = Container.newBuilder().withDescription("1").withSize(1, 1, 3).withEmptyWeight(1)
				.withMaxLoadWeight(41).build();

		Container container2 = Container.newBuilder().withDescription("2").withSize(2, 4, 4).withEmptyWeight(1)
				.withMaxLoadWeight(61).build();

		Container container3 = Container.newBuilder().withDescription("3").withSize(6, 2, 2).withEmptyWeight(1)
				.withMaxLoadWeight(76).build();

		Container container4 = Container.newBuilder().withDescription("4").withSize(2, 4, 6).withEmptyWeight(1)
				.withMaxLoadWeight(81).build();

		Container container5 = Container.newBuilder().withDescription("5").withSize(4, 4, 6).withEmptyWeight(1)
				.withMaxLoadWeight(101).build();

		

		LargestAreaFitFirstPackager packager = LargestAreaFitFirstPackager.newBuilder()
				.withContainers(Arrays.asList(container2,container1,container5,container4,container3)).build();
		List<StackableItem> products = new ArrayList<StackableItem>();

		products.add(new StackableItem(
				Box.newBuilder().withId("4e66de65-0079-497a-b8ed-c2f4066911ee").withSize(5,1,3).withRotate3D().withWeight(60).build(), 1));

		

		List<Container> fits = packager.packList(products, 100);
		System.out.println(fits);

**Comment by skjolber** [comment]
@souravdalal Yes, the containers must be sorted. This is a feature, not a bug.

**Comment by souravdalal** [comment]
Hi @skjolber , Can you please let me know what is the criteria for Sort( which attributes). As there could be same weight with different dimension. Also, being a new one I have one more findings , if container size is 50*40*30 & product size is 20*30*40, with 2 quantities then it requires 2 containers but if Container Size is 30*40*50 (same but order is different) with same product size & qunatity (i.e. 2) then required container is 1 only. Can you please help me in understanding the logic.
Sorry for bothering you again.

**Comment by skjolber** [comment]
@souravdalal the containers must be listed in order, from best (index 0) to worst (index n - 1). Sorting of the contaienrs is application-specific, reasons might be

* volume
* weight capactiy
* different dimensions (i.e. same volume but different shape)
* container cost (i.e. custom shape)
* shipping cost

Also the LAFF algorithm is not that great for certain usecases. It picks a first box then runs a layer by layer packaging, leaving a lot of free room. Rather try the Plain packager (see 'Algorithm details' section in the readme).
