### ISSUE TITLE
[Feature Request] Remainder of what does not fit

### ISSUE THREAD

**Issue by mores** [skjolber/3d-bin-container-packing#612]
The current implementation for multiple containers is:
`List<Container> fits = packager.packList(products, maxContainers, deadline);`

My use case:
  25 StackableItems
  10 StackableItems Per Container

Round 1
After `List<Container> fits = packager.packList(products, 9999, deadline);`
I would expect fits.size() == 3

Round 2
Now I want to set  maxContainers = fits.size() - 1;
I need to know which 20 are IN the Containers, and which 5 did NOT make it into any Container

**Comment by skjolber** [comment]
@more but the result in round 2 will just be the two first containers from round 1?
