### ISSUE TITLE
Number of containers incorrects in LargestAreaFitFirstPackager rotate 3d=false and footprintFirst = false

### ISSUE THREAD

**Issue by gargolillas** [skjolber/3d-bin-container-packing#62]
In this example, number of containers is 1 but algorithm  return 2.
Maybe recursivity is not correct? The problem is that a box of high=112 is in the second level of container one, when can be put on the level one, position 64x34,  to optimize.

      List<Container> containers = new ArrayList<>();
      containers.add(new Container(128, 55, 224, 0));
      LargestAreaFitFirstPackager packager = new LargestAreaFitFirstPackager(containers, false, false, true);

      List<BoxItem> products = new ArrayList<>();
		
	products.add(new BoxItem(new Box("a", 32, 17, 112, 0), 6));
        products.add(new BoxItem(new Box("b", 27, 37, 37, 0), 6)); 
        products.add(new BoxItem(new Box("c", 35 , 54, 33, 0), 2));

      List<Container> fits = packager.packList(products, Integer.MAX_VALUE, Long.MAX_VALUE);

**Comment by skjolber** [comment]
This algorithm currently selects box 1 by largest area (or highest) and then the next boxes by largest volume. So for the above code first 1x a but then 2x c. Also it places those boxes so that the single free space is maximized (i.e. one large space is better than two smaller spaces (even if they together are larger). I guess adding different strategies would be possible.

**Comment by skjolber** [comment]
See the above code in action at https://github.com/skjolber/3d-bin-container-packing/pull/61

**Comment by gargolillas** [comment]
Excuse me,
But in this exemple, Box 'B' and 'C' have minus volumen than 'A', then all box can be fit in one level, but algorithm return two levels. I'm wrong? The five box 'A' can be fit in position 32x34 but algorithm return 64x0, then Box 'C' put in second level.

                products2.add(new BoxItem(new Box("A", 32, 17,  112, 0), 6));
		products2.add(new BoxItem(new Box("B", 32, 54, 27, 0), 1));
		products2.add(new BoxItem(new Box("C", 27, 42, 35, 0), 1));

Thank you

**Comment by gargolillas** [comment]
Another example more simple:
                   containers.add(new Container(128, 55, 224, 0));
                   products2.add(new BoxItem(new Box("C", 27, 42, 35, 0), 6));

This 6 box can be fit in the first level, but fit in two levels. Maybe the first iteration of recursivity has not to eliminate the first box previously ? I'm not sure.

**Comment by skjolber** [comment]
The algorithm is guessing all the time, as it processes one box at a time. It will not make the best decitions. However that does not mean there cannot be any bugs - can you attempt to trace into the code and see which decitions make up the first level?

I guess it would be possible to add more strategies - like 'minimize wasted space' or 'find boxes which are the same height' or something like that.

**Comment by skjolber** [comment]
Yeah, should really have a better visualization tool, like in javascript.

**Comment by skjolber** [comment]
The problem is not the remainder for the first box, you can easily write a test for 4 (2x2) matrix which tests for that.
