### ISSUE TITLE
The result is not accurate

### ISSUE THREAD

**Issue by poo0054** [skjolber/3d-bin-container-packing#628]
hi,I used a more complex scenario.The result is different from what I expected
picture:
![62473791a40966660c30ee79985f2de](https://user-images.githubusercontent.com/85894494/218362676-9660d3aa-b542-40a4-9645-08503ee0734e.png)
![8dc918fd760993a863ee5b409c202ff](https://user-images.githubusercontent.com/85894494/218362686-96712699-949d-49f6-8297-61e6561ae490.jpg)

```java
@Test
    public void testList() {
        List<Container> containers = new ArrayList<>();
        containers.add(Container.newBuilder().withDescription("a").withEmptyWeight(0).withSize(10, 10, 10)
            .withMaxLoadWeight(100).build());
  LargestAreaFitFirstPackager packager =
            LargestAreaFitFirstPackager.newBuilder().withContainers(containers).build();

        List<StackableItem> StackableItems = new ArrayList<>();
 StackableItems.add(new StackableItem(
            Box.newBuilder().withId("1").withSize(10, 10, 2).withWeight(0).withRotate3D().build(), 1));
        StackableItems.add(new StackableItem(
            Box.newBuilder().withId("2").withSize(10, 10, 2).withWeight(0).withRotate3D().build(), 1));
        StackableItems.add(new StackableItem(
            Box.newBuilder().withId("3").withSize(10, 6, 3).withWeight(0).withRotate3D().build(), 1));
		StackableItems.add(new StackableItem(
				Box.newBuilder().withId("5").withSize(10, 6, 4).withWeight(0).withRotate3D().build(), 1));
		StackableItems.add(new StackableItem(
            Box.newBuilder().withId("4").withSize(10, 6, 3).withWeight(0).withRotate3D().build(), 1));

        List<Container> packaging = packager.packList(StackableItems, 1000);
 }
    }
```

**Comment by poo0054** [comment]
hi .To solve this problem, I tried to get the stackValue of the largest box. I changed this method  ;

And in firstStackValuePointComparator.accept, I think it is unnecessary, not necessarily the largest area;

> Here is my address:
https://github.com/poo0054/3d-bin-container-packing/blob/study_2.1.4/core/src/main/java/com/github/skjolber/packing/packer/laff/LargestAreaFitFirstPackager.java

**Comment by skjolber** [comment]
Hi, the LAFF algorithm is not very intelligent. Did you try the "plain packager" or the brute force packager?

**Comment by poo0054** [comment]
In my scenario, it is not suitable for brute force analysis. I need to use multiple boxes to load multiple goods and find the optimal solution.

**Comment by poo0054** [comment]
Thank you very much for the open source, it saves a lot of my time.
