### ISSUE TITLE
How to incorporate visualization?

### ISSUE THREAD

**Issue by rnarvaeza** [skjolber/3d-bin-container-packing#636]
Hello, I've been using this development importing it as a dependency in my pom.xml, I have a question about how to raise the visual layer with three.js. How should I import it or incorporate it into my project? I would really appreciate your help. Thank you

**Comment by skjolber** [comment]
This is currently not possible, the visualizer is just a tool, not very well suited as stacking instructions.

**Comment by skjolber** [comment]
@rnarvaeza the project would need another module for this kind of funcationality, i.e. some kind of step by step visualization.

**Comment by skjolber** [comment]
It is not that it cannot be used, it is more that to the novel user, it is quite lacking.

 * box metadata / labeling
 * box direction
 * no good for printing on paper
 * for larger / big goods, the physics of the human body (in general or a specific individual) has not been taken into account
 * no "transactions" for multi-stop delivery
 
 But I'd be interested in known what your requirements are.
