### ISSUE TITLE
Feature request: Accessing initial container dimension

### ISSUE THREAD

**Issue by suchwerk** [skjolber/3d-bin-container-packing#637]
I have the need to do some test of a Dimension that should fit in a Container. My use case is to filter a list of Containers (Package Material) to match some Carrier criterias especially the min/max size.

After upgrading to the api my old test does not work anymore:
```
                public boolean test(Container material) {
                        return max.canHold3D(material) && material.canHold3D(min);
                }
```       

`material.getStackValues()[0]` should give my access to the x,y,z of the Container built with the builder. 

It would be nice if there is a getDimension function on the Container object, which returns the Dimension used in the builder.

**Comment by skjolber** [comment]
@suchwerk what about the `Container` method ` canLoad`?

**Comment by skjolber** [comment]
Closed for lack of feedback
