### ISSUE TITLE
计算有误 实际上能放进去 算法算不进去

### ISSUE THREAD

**Issue by zhangguishannew** [skjolber/3d-bin-container-packing#659]
containers.add(Container.newBuilder().withDescription("Z001").withEmptyWeight(1).withSize(230, 130, 80).withMaxLoadWeight(100000).build());
		LargestAreaFitFirstPackager packager = LargestAreaFitFirstPackager.newBuilder().withContainers(containers).build();

		List<StackableItem> products = new ArrayList<>();

		products.add(new StackableItem(Box.newBuilder().withDescription("A").withRotate3D().withSize(120, 95, 45).withWeight(1).build(), 1));
		products.add(new StackableItem(Box.newBuilder().withDescription("B").withRotate3D().withSize(105, 80, 60).withWeight(1).build(), 1));
		products.add(new StackableItem(Box.newBuilder().withDescription("C").withRotate3D().withSize(19, 19, 30).withWeight(1).build(), 1));

**Comment by skjolber** [comment]
The calculation is wrong. It can actually be included, but the algorithm cannot be included.

**Comment by skjolber** [comment]
The algorithm will not find all the possible solutions.
