### ISSUE TITLE
Box rotation rule inquiry: how to keep bottom always at the bottom?

### ISSUE THREAD

**Issue by UoUoio** [skjolber/3d-bin-container-packing#670]
How can I set the rotation rule for the box? I want the bottom of the box to always remain at the bottom during calculations and not be rotated to the side or top. I have looked through the documentation, but have not found any information on this topic.

**Comment by khorchanov** [comment]
By default if you don't do `.withRotate3D()` on your Boxes they won't be rotated on the side neither upside down.
You can even force it using `.withRotate2D()`

**Comment by UoUoio** [comment]
Thank you, I understand now. Perhaps my level is just too low...
