### ISSUE TITLE
Incorrect module-info.java

### ISSUE THREAD

**Issue by Insomniac66** [skjolber/3d-bin-container-packing#682]
I may be mistaken since I haven't programmed much Java since well before Java 9, but I believe the `module-info.java` specifically in the core module is incorrect.

It contains the following exports:
```
exports com.github.skjolber.packing.packager;
exports com.github.skjolber.packing.packager.bruteforce;
exports com.github.skjolber.packing.packager.laff;
exports com.github.skjolber.packing.packager.plain;
```

These packages don't exist, instead the relevant packages and classes appear to be located within `com.github.skjolber.packing.packer`, so it should read:

```
exports com.github.skjolber.packing.packer;
exports com.github.skjolber.packing.packer.bruteforce;
exports com.github.skjolber.packing.packer.laff;
exports com.github.skjolber.packing.packer.plain;
```

**Comment by skjolber** [comment]
Fix in 3.0.3
