### ISSUE TITLE
Visualization tool

### ISSUE THREAD

**Issue by skjolber** [skjolber/3d-bin-container-packing#69]
Some kind of visualization tool would be very helpful during development. Probably generation of some JSON file which can be feed into a javascript application.

**Comment by dazito** [comment]
Hi Thomas, do you have any draft/proposal for the JSON structure? I can help you implementing it.

**Comment by skjolber** [comment]
@dazito I guess the most interesting for visualization is Spaces, which have parent-child relationship with other Spaces. Applied to Container, with a list of Levels, Placements specify where one or more Box are placed within those Spaces.

**Comment by skjolber** [comment]
@dazito so it would be possible to visualize both the resulting placements, including hints for following the packaging logic.

**Comment by dazito** [comment]
@skjolber my initial question was more in the sense of data structure to pass on to the frontend/UI. I am using this library no my backend and it is not so straight forward how to retrieve the placement positions from a `Container`, there is the need to code around it a bit - as far as I understand it.

My initial iteration would be first to make some sort of protocol in JSON and then iterate over it.

Something like (from a `Container` object or a possible higher level class) generate the following JSON:
```
{
  "stackWeight": 100,
  "stackHeight": 50,
  "placements": [
    {
      "x": 0,
      "y": 0,
      "z": 0,
      "width": 5,
      "length": 10,
      "height": 15
    },
    (...)
  ]
}
```

I don't see much of a benefit to add some UI component to the library, IMO that should be on a different project or a new folder within the repository but decoupled with the library.

**Comment by skjolber** [comment]
@dazito right, I agree. Do you know some visualization library already (with some well-defined input format)?

**Comment by dazito** [comment]
@skjolber I have read about d3.js and three.js. They are more like library/framework to generate charts, objects and so on.

PS: Take this with a grain of salt, I am not a front end developer 😃

**Comment by skjolber** [comment]
Well I'm not a front end developer either, so will have to shop the web for a solution. Came across this: https://www.youtube.com/watch?v=tQPdBg9_k-4

**Comment by skjolber** [comment]
@dazito I got in touch with the author, @chadiik, and the project is actually open source:

https://github.com/chadiik/freight-packer 

He points to https://github.com/chadiik/freight-packer/tree/master/src/api/view and recommends vscode for code docs and easy navigation to types definitions.

**Comment by dazito** [comment]
That looks quite neat! In case you didn't notice, the repo is here: https://github.com/chadiik/freight-packer.

It seems it uses it's own 3d packing algorithm implementation. I will try to integrate it with your lib over the next weekends.

**Comment by dazito** [comment]
Just a small heads up.
My lack of knowledge in Three.js was dragging me quite a lot so I decided to implement my own visualization tool with Angular and canvas. For now it is only displaying in 2D, I will create a PR tomorrow or next weekend.

Nevertheless if someone can integrate with https://github.com/chadiik/freight-packer please do so :)

**Comment by EmilioSanJose** [comment]
Looking forward to it dazito!

**Comment by dazito** [comment]
These two commits are the first draft:
https://github.com/dazito/3d-bin-container-packing/commit/74e2ce04f3082d0d6ce8a849b0fe892b652d493d

https://github.com/dazito/3d-bin-container-packing/commit/74e2ce04f3082d0d6ce8a849b0fe892b652d493d

Instructions on how to run the visualization app (angular):
https://github.com/dazito/3d-bin-container-packing/tree/master/vis-tool

On 3d-bin-container-packing call the `toFile` method in the Container object, and pass in the path to the file. Then on the webapp click on "Browse" and select the file you passed in to `toFile`.

I want to polish things a bit and improve documentation, then I will create a PR.

PS; There may be bugs here and there, I did not test it that much. Please report any bugs you find.

**Comment by venkatalokesh8** [comment]
hey @skjolber  can you attach sample JSON file

**Comment by skjolber** [comment]
Hi @venkatalokesh8 did not see this before now. I'll add a JSON format to the container / box / space classes shortly.

**Comment by skjolber** [comment]
Finally made a three.js visualizer.
