### ISSUE TITLE
Calculate volume

### ISSUE THREAD

**Issue by thomasV92** [skjolber/3d-bin-container-packing#7]
Dear skjolber,

Thanks for this great code!
I had some problems with using your code when the dimensions are getting bigger. (working with mm) At that point, the code is not running anymore. I found out that the problem was caused by the fact that when volume = depth * width * height is bigger as what an int variable could handle.  To solve this I changed the variable type of volume in the dimensions class to the long variable type and I also cast the depth, width and height to long. This solves the problem. 

Best regards,
Thomas

**Comment by skjolber** [comment]
Sounds good, will you prepare a pull request for the change?

**Comment by skjolber** [comment]
Changed volume to long type.
