### ISSUE TITLE
4 items with same dimensions work only with bruteForce

### ISSUE THREAD

**Issue by Piergi0rgio** [skjolber/3d-bin-container-packing#719]
Maybe i'm doing something wrong but it only works with brute force

	@Test
	public void testFourItems() throws Exception {
		Container container = Container.newBuilder().withDescription("Desc").withEmptyWeight(0).withSize(80, 120, 15)
				.withMaxLoadWeight(1).build();
		List<Container> containers = new ArrayList<>();
		containers.add(container);
		List<ContainerItem> containerItems = ContainerItem.newListBuilder().withContainers(containers).build();

		// Item(s) x 4
		List<StackableItem> products = new ArrayList<StackableItem>();
		products.add(new StackableItem(Box.newBuilder().withId("030261").withDescription("Test Item")
				.withSize(60, 40, 13).withWeight(0).withRotate2D().build(), 4));
		
		FastBruteForcePackager packager = FastBruteForcePackager.newBuilder().build();
		// return 2 containers PlainPackager packager = PlainPackager.newBuilder().build();
		// return 2 containers LargestAreaFitFirstPackager packager = LargestAreaFitFirstPackager.newBuilder().build();
		List<Container> containersResult = packager.packList(products, containerItems, 25);

		write(containersResult);
	}
![brute](https://github.com/skjolber/3d-bin-container-packing/assets/80316041/09efce1d-f647-4375-9996-2066d11d8b73)
![plain](https://github.com/skjolber/3d-bin-container-packing/assets/80316041/04e593b2-4df7-438a-ab51-d24fac2eb966)

**Comment by skjolber** [comment]
This is the expected behaviour.
