### ISSUE TITLE
Index -1 while running visualizer

### ISSUE THREAD

**Issue by tiaggofg** [skjolber/3d-bin-container-packing#745]
Hello!

I'm using the visualizer API in my application and when executing the DefaultPackagingResultVisualizerFactory#visualize method it gets an error due to an index -1 being passed to the Point3DFlagList#get method. Below is the stack trace that I received

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at com.github.skjolber.packing.ep.points3d.Point3DFlagList.get(Point3DFlagList.java:63)
	at com.github.skjolber.packing.ep.points3d.ExtremePoints3D.add(ExtremePoints3D.java:117)
	at com.github.skjolber.packing.visualizer.packaging.DefaultPackagingResultVisualizerFactory.visualize(DefaultPackagingResultVisualizerFactory.java:74)
```

I have a list of 20 containers with a fixed base (width and length) and height varying from 5% of the initial value. In addition, I have a list of items that need to be packed in these 20 containers using the LAFF algorithm.

I see that it occurs due to the ExtremePoint3D#findPoint method return -1. So you explain why this error occurs and how I can fix it?

**Comment by skjolber** [comment]
The visualizer does not work for LAFF because it tries to calculate the free points of the load space, while the LAFF essensiellt changes the load space for each level. So -1 is basically because a point is not found where the box is placed.

**Comment by tiaggofg** [comment]
But is it possible to implement a visualizer for LAFF?

In addition, I think that is a good idea to print a log with your above explanation and a suggestion to use another algorithm or, to implement your visualizer - of course if it's possible.

**Comment by tiaggofg** [comment]
I'm using version 3.0.7 with maven

```
<dependency>
    <groupId>com.github.skjolber.3d-bin-container-packing</groupId>
    <artifactId>core</artifactId>
    <version>${bin-container-packaging.version}</version>
</dependency>

<dependency>
    <groupId>com.github.skjolber.3d-bin-container-packing</groupId>
    <artifactId>visualizer-api</artifactId>
    <version>${bin-container-packaging.version}</version>
</dependency>
```

**Comment by tiaggofg** [comment]
Wow, it's work!! Is there a forecast of when the changes will be available in Maven?

**Comment by skjolber** [comment]
Try 3.0.8
