### ISSUE TITLE
Not able to understand the output.

### ISSUE THREAD

**Issue by balachandarsv** [skjolber/3d-bin-container-packing#78]
```
  List<Container> containers = new ArrayList<Container>();

  containers.add(new Container("Cont",30, 30, 30, 500)); // x y z and weight

  Packager packager = new LargestAreaFitFirstPackager(containers,false,true,true);

  List<BoxItem> products = new ArrayList<BoxItem>();

  products.add(new BoxItem(new Box("A", 10, 10, 10, 25), 10));

```

For the above code, I get the following placements.

Placement [0x0x0, width=10, depth=10, height=10]
Placement [0x10x0, width=10, depth=10, height=10]
Placement [0x20x**10**, width=10, depth=10, height=10]
Placement [10x0x0, width=10, depth=10, height=10]
Placement [10x10x0, width=10, depth=10, height=10]
Placement [10x20x**10**, width=10, depth=10, height=10]
Placement [20x0x0, width=10, depth=10, height=10]
Placement [20x10x**10**, width=10, depth=10, height=10]
Placement [20x20x**10**, width=10, depth=10, height=10]
Placement [0x0x**10**, width=10, depth=10, height=10]

May I know why is the Z value "10", but the level is still 0?

I thought the z-value would be 0 for all the cases as its still on level 0.

**Comment by skjolber** [comment]
@balachandarsv I've not to investigate much, but this seems like a bug. All stacking is at the level ground level.
