### ISSUE TITLE
Some boxes are floating.

### ISSUE THREAD

**Issue by jiang-yuan** [skjolber/3d-bin-container-packing#86]
It seems that LAFF does not consider the constraint of stability or basement of a box. When I visualize the solution, I found that some of the boxes are floating and without the basement.

**Comment by skjolber** [comment]
@jiang-yuan yes, that is the nature of the LAFF - level by level. I've got an issue for stacking in 'real' 3D here: https://github.com/skjolber/3d-bin-container-packing/issues/48

Also, what kind of visualization are you using?

**Comment by jiang-yuan** [comment]
The tool that we use is https://docs.enthought.com/mayavi/mayavi/.
I need to find a simple way to add the stability constraint to LAFF without considering the volume utilization. I saw the issue 48 and I found that none of your reference paper mentions this. Do you have ideas about this problem?

**Comment by skjolber** [comment]
@jiang-yuan not really, stacking requires another algorithm to work properly.
