### ISSUE TITLE
Incorrect free space calculation

### ISSUE THREAD

**Issue by dazito** [skjolber/3d-bin-container-packing#98]
If I understand it right, this unit test is failing but it should pass

    @Test
    public void testFreeSpace() {
        List<Container> containerList = Collections.singletonList(
                new Container(50, 50, 50, 50)
        );

        List<BoxItem> boxList = new ArrayList<>();
        boxList.add(new BoxItem(new Box(25, 25, 25, 50)));

        Packager packager = new LargestAreaFitFirstPackager(containerList, false, true, true);

        Container containerPack = packager.pack(boxList);
        Dimension freeSpace = containerPack.getFreeSpace();

        System.out.println(freeSpace);

        Assert.assertEquals(25, freeSpace.getDepth());
        Assert.assertEquals(25, freeSpace.getHeight());
        Assert.assertEquals(25, freeSpace.getWidth());
        Assert.assertEquals(62500, freeSpace.getVolume());

    }

If I place a box with half the size (and volume) of the container I expect the free space to be the other remaining half but in this case only the height and volume seems to be calculated correctly (depth and width have wrong values)

println is printing to the console:
Dimension [width=50, depth=50, height=25, volume=62500]

Where
width=50 ❌ 
depth=50 ❌ 
height=25 🆗 
volume=62500 🆗 

I expected something like:
Dimension [width=25, depth=25, height=25, volume=62500]

PS; This behavior also happens with more than one BoxItem

**Comment by skjolber** [comment]
The method name should be changed, it calculates the free space for a new level, not the free space (i.e. air gaps) within the container. There is a method getUsedSpace() which calculates the bounding box though, would it work better?

**Comment by skjolber** [comment]
@dazito any further input?

**Comment by dazito** [comment]
I have been quite busy lately, I agree that the method name is a bit misleading and changing it name can be a good solution. Maybe first tag it as deprecated while creating a new method that is just the renaming of getFreeSpace() so we suddenly do not break the build to those updating to the new version. 

Regarding the usage of getUsedSpace(), I will try it out on my use case and report back soon.
